import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SidebarDashBoard from "@/app/dashboard/sidebardashboard";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={cn(
            "rounded-md flex flex-col md:flex-row bg-gray-100 dark:bg-neutral-800 w-full flex-1  mx-auto border border-neutral-200 dark:border-neutral-700 overflow-hidden",
            "h-screen bg-[#F4F7FE]"
          )}
        >
          <SidebarDashBoard></SidebarDashBoard>
          <div className="w-full h-full px-10 py-14">{children}</div>
        </div>
      </body>
    </html>
  );
}
